In [1]:
import pandas as pd 
mapper = pd.read_csv("data/processed/mappings_v2/products__TO__olist_products_dataset_mapping_suggestions_flat.csv")

In [2]:
mapper_sorted = mapper.sort_values("confidence", ascending=False)
mapper_sorted.head(30)

     source_column               target_column  confidence
5       product_id                  product_id    1.000000
10    product_name       product_category_name    0.740254
11    product_name         product_name_lenght    0.663126
15     supplier_id                  product_id    0.653377
0      category_id                  product_id    0.562708
12    product_name                  product_id    0.527504
6       product_id         product_name_lenght    0.505229
1      category_id       product_category_name    0.423957
7       product_id  product_description_lenght    0.416141
13    product_name  product_description_lenght    0.403816
25  units_in_stock            product_weight_g    0.401501
8       product_id       product_category_name    0.388904
26  units_in_stock           product_length_cm    0.372371
14    product_name            product_weight_g    0.370642
27  units_in_stock         product_name_lenght    0.368833
9       product_id            product_weight_g    0.364987
28  units_in_stock          product_photos_qty    0.351677
20      unit_price            product_weight_g    0.351636
29  units_in_stock            product_width_cm    0.347828
21      unit_price  product_description_lenght    0.345050
22      unit_price         product_name_lenght    0.338778
16     supplier_id         product_name_lenght    0.326577
23      unit_price           product_height_cm    0.317766
24      unit_price           product_length_cm    0.314731
17     supplier_id  product_description_lenght    0.270943
18     supplier_id            product_weight_g    0.238157
19     supplier_id          product_photos_qty    0.238100
2      category_id         product_name_lenght    0.226794
3      category_id  product_description_lenght    0.215684
4      category_id            product_weight_g    0.146806

In [9]:
oi = pd.read_csv("data/processed/mappings_v2/products__TO__olist_order_items_dataset_mapping_suggestions_flat.csv")

In [10]:
oi_sorted = mapper.sort_values("confidence", ascending=False)
oi_sorted.head(30)

     source_column               target_column  confidence
5       product_id                  product_id    1.000000
10    product_name       product_category_name    0.740254
11    product_name         product_name_lenght    0.663126
15     supplier_id                  product_id    0.653377
0      category_id                  product_id    0.562708
12    product_name                  product_id    0.527504
6       product_id         product_name_lenght    0.505229
1      category_id       product_category_name    0.423957
7       product_id  product_description_lenght    0.416141
13    product_name  product_description_lenght    0.403816
25  units_in_stock            product_weight_g    0.401501
8       product_id       product_category_name    0.388904
26  units_in_stock           product_length_cm    0.372371
14    product_name            product_weight_g    0.370642
27  units_in_stock         product_name_lenght    0.368833
9       product_id            product_weight_g    0.364987
28  units_in_stock          product_photos_qty    0.351677
20      unit_price            product_weight_g    0.351636
29  units_in_stock            product_width_cm    0.347828
21      unit_price  product_description_lenght    0.345050
22      unit_price         product_name_lenght    0.338778
16     supplier_id         product_name_lenght    0.326577
23      unit_price           product_height_cm    0.317766
24      unit_price           product_length_cm    0.314731
17     supplier_id  product_description_lenght    0.270943
18     supplier_id            product_weight_g    0.238157
19     supplier_id          product_photos_qty    0.238100
2      category_id         product_name_lenght    0.226794
3      category_id  product_description_lenght    0.215684
4      category_id            product_weight_g    0.146806

In [11]:
seller = pd.read_csv("data/processed/mappings_v2/products__TO__olist_sellers_dataset_mapping_suggestions_flat.csv")
seller_sorted = mapper.sort_values("confidence", ascending=False)
seller_sorted.head(30)

     source_column               target_column  confidence
5       product_id                  product_id    1.000000
10    product_name       product_category_name    0.740254
11    product_name         product_name_lenght    0.663126
15     supplier_id                  product_id    0.653377
0      category_id                  product_id    0.562708
12    product_name                  product_id    0.527504
6       product_id         product_name_lenght    0.505229
1      category_id       product_category_name    0.423957
7       product_id  product_description_lenght    0.416141
13    product_name  product_description_lenght    0.403816
25  units_in_stock            product_weight_g    0.401501
8       product_id       product_category_name    0.388904
26  units_in_stock           product_length_cm    0.372371
14    product_name            product_weight_g    0.370642
27  units_in_stock         product_name_lenght    0.368833
9       product_id            product_weight_g    0.364987
28  units_in_stock          product_photos_qty    0.351677
20      unit_price            product_weight_g    0.351636
29  units_in_stock            product_width_cm    0.347828
21      unit_price  product_description_lenght    0.345050
22      unit_price         product_name_lenght    0.338778
16     supplier_id         product_name_lenght    0.326577
23      unit_price           product_height_cm    0.317766
24      unit_price           product_length_cm    0.314731
17     supplier_id  product_description_lenght    0.270943
18     supplier_id            product_weight_g    0.238157
19     supplier_id          product_photos_qty    0.238100
2      category_id         product_name_lenght    0.226794
3      category_id  product_description_lenght    0.215684
4      category_id            product_weight_g    0.146806

In [13]:
import pandas as pd

order_items_path = r"C:/Users/yessine/ai_journey/projects/stage/data/olist_order_items_dataset.csv"
sellers_path     = r"C:/Users/yessine/ai_journey/projects/stage/data/olist_sellers_dataset.csv"

print("ORDER_ITEMS columns:\n", pd.read_csv(order_items_path, nrows=5).columns)
print("SELLERS columns:\n", pd.read_csv(sellers_path, nrows=5).columns)

ORDER_ITEMS columns:
 Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='object')
SELLERS columns:
 Index(['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state'], dtype='object')

In [14]:
import pandas as pd

out_path = r"data/processed/mappings_v2/products__TO__olist_order_items_dataset_mapping_suggestions_flat.csv"
mapper = pd.read_csv(out_path)

mapper.sort_values("confidence", ascending=False).head(30)

     source_column  target_column  confidence
5       product_id     product_id    1.000000
20      unit_price          price    0.724028
6       product_id      seller_id    0.705789
15     supplier_id      seller_id    0.678180
16     supplier_id       order_id    0.654084
17     supplier_id     product_id    0.653377
7       product_id       order_id    0.610971
18     supplier_id  order_item_id    0.594831
8       product_id  order_item_id    0.592434
0      category_id     product_id    0.562708
1      category_id       order_id    0.556757
2      category_id  order_item_id    0.532862
10    product_name     product_id    0.527504
3      category_id      seller_id    0.511784
21      unit_price  freight_value    0.469693
25  units_in_stock          price    0.422663
26  units_in_stock  freight_value    0.413386
9       product_id          price    0.348207
11    product_name      seller_id    0.301080
27  units_in_stock     product_id    0.290364
19     supplier_id          price    0.287134
12    product_name          price    0.282241
28  units_in_stock      seller_id    0.280171
22      unit_price     product_id    0.276607
23      unit_price      seller_id    0.274581
29  units_in_stock       order_id    0.239859
13    product_name  order_item_id    0.226131
14    product_name       order_id    0.215866
24      unit_price  order_item_id    0.195478
4      category_id          price    0.187028